In [1]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import fetch_mldata
import matplotlib.pyplot as plt
from sklearn import datasets, svm, metrics
from sklearn import cross_validation
#from sklearn.neural_network import MLPClassifier
from sklearn import tree
import time 
from sklearn import neighbors
from sklearn.utils import shuffle
tf.logging.set_verbosity(tf.logging.ERROR)
from sklearn.naive_bayes import BernoulliNB

C:\Users\steja\Anaconda2\envs\tensorflow\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
mnist = fetch_mldata("MNIST original")

In [3]:
print(mnist.data.shape)

(70000, 784)


In [4]:
print(np.unique(mnist.target))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [5]:
X, y = np.float32(mnist.data[:70000]), np.float32(mnist.target[:70000])
X, y = shuffle(X,y)

In [6]:
#X, y = np.float32(mnist.data[:70000]), np.float32(mnist.target[:70000])
X_train, y_train = np.float32(X[:15000]), np.float32(y[:15000])
X_test, y_test = np.float32(X[60000:]), np.float32(y[60000:])

In [7]:
start = int(round(time.time() * 1000))

In [8]:
BB = BernoulliNB()
BB.fit(X_train,y_train)
end = int(round(time.time() * 1000))
print("--NN fitting finished in ", (end-start), "ms--------------")
predicted=BB.predict(X_test)
expected=y_test

--NN fitting finished in  846 ms--------------


In [9]:
print(cross_validation.cross_val_score(BB, X_train,y_train, cv=5))

[ 0.82256991  0.83083583  0.82894298  0.81954636  0.83578104]


In [10]:
print("Classification report for kNN classifier %s:\n%s\n"
     % (BB, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

Classification report for kNN classifier BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True):
             precision    recall  f1-score   support

        0.0       0.91      0.91      0.91      1041
        1.0       0.88      0.95      0.91      1122
        2.0       0.89      0.83      0.86      1032
        3.0       0.75      0.79      0.77       968
        4.0       0.80      0.80      0.80       999
        5.0       0.80      0.68      0.74       874
        6.0       0.88      0.90      0.89       971
        7.0       0.91      0.85      0.88      1032
        8.0       0.77      0.76      0.76       984
        9.0       0.70      0.79      0.74       977

avg / total       0.83      0.83      0.83     10000


Confusion matrix:
[[ 944    1    3    7    4   38   18    0   24    2]
 [   0 1071   10    2    1   16    7    0   14    1]
 [  16   12  860   25   17    2   38   18   42    2]
 [   9   25   32  762    1   22   10    9   52   46]
 [   2    6    5 

In [11]:
print("Accuracy is:",round(metrics.accuracy_score(expected,predicted)*100,2))

Accuracy is: 82.95


In [12]:
print("Test error is:",100-round(metrics.accuracy_score(expected,predicted)*100,2))

Test error is: 17.05
