In [2]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import fetch_mldata
import matplotlib.pyplot as plt
from sklearn import datasets, svm, metrics
from sklearn import cross_validation
#from sklearn.neural_network import MLPClassifier
from sklearn import tree
import time 
from sklearn import neighbors
from sklearn.utils import shuffle
tf.logging.set_verbosity(tf.logging.ERROR)

In [3]:
mnist = fetch_mldata("MNIST original")

In [4]:
print(mnist.data.shape)

(70000, 784)


In [5]:
print(np.unique(mnist.target))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [6]:
X, y = np.float32(mnist.data[:70000]), np.float32(mnist.target[:70000])
X, y = shuffle(X,y)

In [7]:
#X, y = np.float32(mnist.data[:70000]), np.float32(mnist.target[:70000])
X_train, y_train = np.float32(X[:15000]), np.float32(y[:15000])
X_test, y_test = np.float32(X[60000:]), np.float32(y[60000:])

In [8]:
start = int(round(time.time() * 1000))

In [10]:
DT=tree.DecisionTreeClassifier(random_state=1)
DT.fit(X_train,y_train)
predicted=DT.predict(X_test)
expected=y_test

In [12]:
print(cross_validation.cross_val_score(DT, X_train,y_train, cv=5))

[ 0.80919081  0.8015318   0.81433333  0.80787191  0.82309746]


In [13]:
end = int(round(time.time() * 1000))
print("--NN fitting finished in ", (end-start), "ms--------------")

--NN fitting finished in  108561 ms--------------


In [15]:
print("Classification report for kNN classifier %s:\n%s\n"
     % (DT, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

Classification report for kNN classifier DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='best'):
             precision    recall  f1-score   support

        0.0       0.90      0.91      0.91      1011
        1.0       0.92      0.95      0.93      1129
        2.0       0.76      0.78      0.77       942
        3.0       0.79      0.77      0.78       992
        4.0       0.80      0.77      0.78       935
        5.0       0.76      0.76      0.76       902
        6.0       0.86      0.83      0.85      1004
        7.0       0.87      0.84      0.86      1098
        8.0       0.77      0.74      0.75       967
        9.0       0.74      0.80      0.77      1020

avg / total       0.82    

In [16]:
print("Accuracy is:",round(metrics.accuracy_score(expected,predicted)*100,2))

Accuracy is: 81.86


In [17]:
print("Test error is:",100-round(metrics.accuracy_score(expected,predicted)*100,2))

Test error is: 18.14


In [18]:
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

Confusion matrix:
[[ 922    0    5   14    4   20   15    9   16    6]
 [   1 1069   17    4   10    2    6    5   12    3]
 [  15   16  737   32   14   18   29   26   37   18]
 [   7    7   41  759   10   72    6   20   30   40]
 [   5   13   27   11  718   18   16   13   30   84]
 [  26   13   14   46   19  690   29   11   31   23]
 [  22   10   26    9   31   34  835    7   23    7]
 [   6   11   34   17   22    7    7  925   11   58]
 [  13   22   51   40   23   27   20   14  715   42]
 [   8    4   15   32   52   22    8   34   29  816]]
