In [15]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import fetch_mldata
import matplotlib.pyplot as plt
from sklearn import datasets, svm, metrics
from sklearn import cross_validation
#from sklearn.neural_network import MLPClassifier
from sklearn import tree
import time 
from sklearn import neighbors
from sklearn.utils import shuffle
tf.logging.set_verbosity(tf.logging.ERROR)
from sklearn.naive_bayes import GaussianNB

In [16]:
mnist = fetch_mldata("MNIST original")

In [17]:
print(mnist.data.shape)

(70000, 784)


In [18]:
print(np.unique(mnist.target))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [19]:
X, y = np.float32(mnist.data[:70000]), np.float32(mnist.target[:70000])
X, y = shuffle(X,y)

In [20]:
#X, y = np.float32(mnist.data[:70000]), np.float32(mnist.target[:70000])
X_train, y_train = np.float32(X[:15000]), np.float32(y[:15000])
X_test, y_test = np.float32(X[60000:]), np.float32(y[60000:])

In [21]:
start = int(round(time.time() * 1000))

In [22]:
GB = GaussianNB()
GB.fit(X_train,y_train)
end = int(round(time.time() * 1000))
print("--NN fitting finished in ", (end-start), "ms--------------")
predicted=GB.predict(X_test)
expected=y_test

--NN fitting finished in  263 ms--------------


In [23]:
print(cross_validation.cross_val_score(GB, X_train,y_train, cv=5))

[ 0.58694204  0.58061292  0.56266667  0.56133333  0.59445928]


In [24]:
print("Classification report for kNN classifier %s:\n%s\n"
     % (GB, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

Classification report for kNN classifier GaussianNB(priors=None):
             precision    recall  f1-score   support

        0.0       0.67      0.94      0.78       977
        1.0       0.70      0.95      0.81      1180
        2.0       0.84      0.25      0.39       980
        3.0       0.69      0.67      0.68       987
        4.0       0.88      0.17      0.28       969
        5.0       0.59      0.05      0.10       886
        6.0       0.66      0.93      0.77      1031
        7.0       0.89      0.30      0.45      1066
        8.0       0.37      0.51      0.43       976
        9.0       0.38      0.93      0.54       948

avg / total       0.67      0.58      0.53     10000


Confusion matrix:
[[ 916    0    5    2    1    1   23    1   19    9]
 [   0 1126    2   10    1    4   11    1   13   12]
 [ 119   54  249  153    3    1  228    3  156   14]
 [  63   81    9  659    0    0   34    9   62   70]
 [  42   20    5   12  161   10  110    7  130  472]
 [ 167   36

In [25]:
print("Accuracy is:",round(metrics.accuracy_score(expected,predicted)*100,2))

Accuracy is: 58.33


In [26]:
print("Test error is:",100-round(metrics.accuracy_score(expected,predicted)*100,2))

Test error is: 41.67


In [27]:
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

Confusion matrix:
[[ 916    0    5    2    1    1   23    1   19    9]
 [   0 1126    2   10    1    4   11    1   13   12]
 [ 119   54  249  153    3    1  228    3  156   14]
 [  63   81    9  659    0    0   34    9   62   70]
 [  42   20    5   12  161   10  110    7  130  472]
 [ 167   36    3   70    5   48   62    3  422   70]
 [  10   33   10    0    0    6  962    1    8    1]
 [  14   17    5   25    9    3    1  325   24  643]
 [  21  221    5   20    0    7   35    3  501  163]
 [   7   18    3    4    3    1    1   13   12  886]]
