# Linear Classifier 


In [1]:
from sklearn.datasets import load_digits
from matplotlib import pyplot as plt
from sklearn.datasets import fetch_mldata
from sklearn.cross_validation import train_test_split
from tensorflow.contrib import learn
import tensorflow as tf
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn import metrics
from sklearn.utils import shuffle
import time

C:\Users\saish\Anaconda2\envs\tf\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
m_data = tf.contrib.learn.datasets.mnist.load_mnist()

Extracting MNIST-data\train-images-idx3-ubyte.gz
Extracting MNIST-data\train-labels-idx1-ubyte.gz
Extracting MNIST-data\t10k-images-idx3-ubyte.gz
Extracting MNIST-data\t10k-labels-idx1-ubyte.gz


In [3]:
train_set = m_data.train
train_images = train_set.images
train_labels = train_set.labels.astype(np.int32)

In [4]:
val_set = m_data.validation
val_images = val_set.images
val_labels = val_set.labels.astype(np.int32)

In [5]:
test_set = m_data.test
test_images = test_set.images
test_labels = test_set.labels.astype(np.int32)

In [6]:
image_set = tf.contrib.layers.real_valued_column('', dimension=784)
cls = learn.LinearClassifier(feature_columns=[image_set], n_classes=10)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_num_worker_replicas': 0, '_task_type': None, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_save_summary_steps': 100, '_is_chief': True, '_tf_random_seed': None, '_num_ps_replicas': 0, '_model_dir': 'C:\\Users\\saish\\AppData\\Local\\Temp\\tmp403r77ws', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_master': '', '_evaluation_master': '', '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000257412E4940>, '_environment': 'local', '_session_config': None}


In [7]:
start = int(round(time.time() * 1000))

In [8]:
cls.fit(train_images, train_labels , steps=2000)

Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Sav

LinearClassifier(params={'gradient_clip_norm': None, 'joint_weights': False, 'feature_columns': [_RealValuedColumn(column_name='', dimension=784, default_value=None, dtype=tf.float32, normalizer=None)], 'optimizer': None, 'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x00000257412E4668>})

In [9]:
end = int(round(time.time() * 1000))
print("--NN fitting finished in ", (end-start), "ms--------------")

--NN fitting finished in  562256 ms--------------


# Validation set prediction

In [10]:
val_pred = list(cls.predict(val_images, as_iterable=True))


score = metrics.accuracy_score(val_labels, val_pred)
print ('Test Accuracy', score)
Recall = metrics.recall_score(val_labels, val_pred, average='weighted')
print('Test Recall', Recall)
Precision = metrics.precision_score(val_labels, val_pred, average='weighted')
print('Test Precision', Precision)
F1 = metrics.f1_score(val_labels, val_pred, average='weighted')
print('F1', F1)
matrix = metrics.confusion_matrix(val_labels, val_pred)
print('Confusion Matrix', matrix)

Instructions for updating:
Please switch to predict_classes, or set `outputs` argument.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
INFO:tensorflow:Restoring parameters from C:\Users\saish\AppData\Local\Temp\tmp403r77ws\model.ckpt-2000
Test Accuracy 0.927
Test Recall 0.927
Test Precision 0.926777337771
F1 0.92683715742
Confusion Matrix [[464   0   0   2   0   6   3   1   2   1]
 [  0 550   3   1   0   4   0   0   5   0]
 [  5   8 435   7   5   1   6   4  15   2]
 [  0   3  15 441   0  19   1   6   3   5]
 [  2   2   7   1 504   0   6   1   4   8]
 [  2   2   3  21   5 379   7   0  12   3]
 [  3   2   0   0   2   5 483   0   5   1]
 [  3   2   4   2   5   0   0 518   1  15]
 [  2   8   8  10   3  12   4   1 410   4]
 [  4   1   0  

In [11]:
print("Classification report for Linear classifier %s:\n%s\n"
     % (cls, metrics.classification_report(val_labels, val_pred)))

Classification report for Linear classifier LinearClassifier(params={'gradient_clip_norm': None, 'joint_weights': False, 'feature_columns': [_RealValuedColumn(column_name='', dimension=784, default_value=None, dtype=tf.float32, normalizer=None)], 'optimizer': None, 'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x00000257412E4668>}):
             precision    recall  f1-score   support

          0       0.96      0.97      0.96       479
          1       0.95      0.98      0.96       563
          2       0.92      0.89      0.90       488
          3       0.90      0.89      0.90       493
          4       0.95      0.94      0.94       535
          5       0.88      0.87      0.88       434
          6       0.95      0.96      0.96       501
          7       0.95      0.94      0.94       550
          8       0.89      0.89      0.89       462
          9       0.92      0.91      0.92       495

avg / total       0.93      0.93     

# Model Testing

In [12]:
y = list(cls.predict(test_images, as_iterable=True))

score = metrics.accuracy_score(test_labels, y)
print ('Test Accuracy', score)
Error = 100-round(metrics.accuracy_score(test_labels, y)*100,2)
print('Test Error', Error)
Recall = metrics.recall_score(test_labels, y, average='weighted')
print('Test Recall', Recall)
Precision = metrics.precision_score(test_labels, y, average='weighted')
print('Test Precision', Precision)
F1 = metrics.f1_score(test_labels, y, average='weighted')
print('F1', F1)
matrix = metrics.confusion_matrix(test_labels, y)
print('Confusion Matrix', matrix)

Instructions for updating:
Please switch to predict_classes, or set `outputs` argument.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
INFO:tensorflow:Restoring parameters from C:\Users\saish\AppData\Local\Temp\tmp403r77ws\model.ckpt-2000
Test Accuracy 0.9233
Test Error 7.67
Test Recall 0.9233
Test Precision 0.923191064542
F1 0.923135419618
Confusion Matrix [[ 960    0    2    2    0    5    8    2    1    0]
 [   0 1110    2    2    0    1    4    2   14    0]
 [   7    9  920   14   10    4   13   11   37    7]
 [   3    0   19  919    0   26    1   12   22    8]
 [   1    2    5    1  915    0   12    3    9   34]
 [  10    2    4   31    9  776   17    7   29    7]
 [  11    3    5    2    9   13  909    3    3    0]
 [   1    6 

In [13]:
print("Classification report for Linear classifier %s:\n%s\n"
     % (cls, metrics.classification_report(test_labels, y)))

Classification report for Linear classifier LinearClassifier(params={'gradient_clip_norm': None, 'joint_weights': False, 'feature_columns': [_RealValuedColumn(column_name='', dimension=784, default_value=None, dtype=tf.float32, normalizer=None)], 'optimizer': None, 'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x00000257412E4668>}):
             precision    recall  f1-score   support

          0       0.95      0.98      0.96       980
          1       0.97      0.98      0.97      1135
          2       0.93      0.89      0.91      1032
          3       0.91      0.91      0.91      1010
          4       0.93      0.93      0.93       982
          5       0.90      0.87      0.89       892
          6       0.93      0.95      0.94       958
          7       0.92      0.92      0.92      1028
          8       0.87      0.89      0.88       974
          9       0.91      0.90      0.91      1009

avg / total       0.92      0.92     