In [16]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import fetch_mldata
import matplotlib.pyplot as plt
from sklearn import datasets, svm, metrics
from sklearn import cross_validation
#from sklearn.neural_network import MLPClassifier
from sklearn import tree
import time 
from sklearn import neighbors
from sklearn.utils import shuffle
tf.logging.set_verbosity(tf.logging.ERROR)
from sklearn.ensemble import RandomForestClassifier

In [17]:
mnist = fetch_mldata("MNIST original")

In [18]:
print(mnist.data.shape)

(70000, 784)


In [19]:
print(np.unique(mnist.target))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [20]:
X, y = np.float32(mnist.data[:70000]), np.float32(mnist.target[:70000])
X, y = shuffle(X,y)

In [21]:
#X, y = np.float32(mnist.data[:70000]), np.float32(mnist.target[:70000])
X_train, y_train = np.float32(X[:15000]), np.float32(y[:15000])
X_test, y_test = np.float32(X[60000:]), np.float32(y[60000:])

In [22]:
start = int(round(time.time() * 1000))
RF=RandomForestClassifier(random_state=1)
RF.fit(X_train,y_train)
end = int(round(time.time() * 1000))
print("--NN fitting finished in ", (end-start), "ms--------------")
predicted=RF.predict(X_test)
expected=y_test

--NN fitting finished in  1920 ms--------------


In [23]:
print(cross_validation.cross_val_score(RF, X_train,y_train, cv=5))

[ 0.91711052  0.9170553   0.91397132  0.91827885  0.9039039 ]


In [24]:
print("Classification report for kNN classifier %s:\n%s\n"
     % (RF, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

Classification report for kNN classifier RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=1, verbose=0, warm_start=False):
             precision    recall  f1-score   support

        0.0       0.94      0.98      0.96       998
        1.0       0.95      0.98      0.96      1191
        2.0       0.91      0.93      0.92       975
        3.0       0.89      0.90      0.90      1015
        4.0       0.92      0.93      0.92       952
        5.0       0.91      0.88      0.90       894
        6.0       0.96      0.94      0.95       999
        7.0       0.94      0.93      0.94      1031
        8.0       0.92      0.85      0.88       958
        9.0       0.9

In [25]:
print("Accuracy is:",round(metrics.accuracy_score(expected,predicted)*100,2))

Accuracy is: 92.39


In [26]:
print("Test error is:",100-round(metrics.accuracy_score(expected,predicted)*100,2))

Test error is: 7.61


In [27]:
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

Confusion matrix:
[[ 974    0    2    3    0    5    7    0    7    0]
 [   0 1171    2    3    3    0    3    4    4    1]
 [   9   10  904   12    8    5    7   10    7    3]
 [   8   10   29  913    0   21    1    8   17    8]
 [  11    2    4    2  881    3    5    2    8   34]
 [   6   11    7   37    9  789    9    8    9    9]
 [   9    6    9    3    7   16  942    0    7    0]
 [   6    9   12    5    7    4    1  961    2   24]
 [   9   14   24   36    9   14    7    5  817   23]
 [   5    3    5    9   35    9    0   23   11  887]]
