In [48]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import fetch_mldata
import matplotlib.pyplot as plt
from sklearn import datasets, svm, metrics
from sklearn import cross_validation
from sklearn.neural_network import MLPClassifier
import time 
from sklearn import neighbors
from sklearn.utils import shuffle
tf.logging.set_verbosity(tf.logging.ERROR)

In [49]:
mnist = fetch_mldata("MNIST original")

In [50]:
print(mnist.data.shape)

(70000, 784)


In [51]:
print(np.unique(mnist.target))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [52]:
X, y = np.float32(mnist.data[:70000]), np.float32(mnist.target[:70000])
X, y = shuffle(X,y)

In [53]:
#X, y = np.float32(mnist.data[:70000]), np.float32(mnist.target[:70000])
X_train, y_train = np.float32(X[:15000]), np.float32(y[:15000])
X_test, y_test = np.float32(X[60000:]), np.float32(y[60000:])

In [54]:
print(type(X_train))
print(type(y_train))
print(type(X_test))
print(type(y_test))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [55]:
print (mnist.data.shape)

(70000, 784)


In [56]:
start = int(round(time.time() * 1000))

In [57]:
clf = MLPClassifier(solver='sgd', activation='relu',alpha=1e-5,hidden_layer_sizes=(200,200), random_state=1)
clf.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(200, 200), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='sgd', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [58]:
end = int(round(time.time() * 1000))
print("--NN fitting finished in ", (end-start), "ms--------------")

--NN fitting finished in  84006 ms--------------


In [59]:
predicted=clf.predict(X_test)
expected=y_test

In [60]:
print(cross_validation.cross_val_score(clf, X_train,y_train, cv=5))

[ 0.91677763  0.9040959   0.91602799  0.91394263  0.91182365]


In [61]:
print("Classification report for Two-hidden layer classifier %s:\n%s\n"
     % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

Classification report for Two-hidden layer classifier MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(200, 200), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='sgd', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False):
             precision    recall  f1-score   support

        0.0       0.96      0.96      0.96       970
        1.0       0.96      0.98      0.97      1064
        2.0       0.89      0.91      0.90       974
        3.0       0.90      0.90      0.90      1032
        4.0       0.91      0.89      0.90       963
        5.0       0.91      0.92      0.92       912
        6.0       0.95      0.93      0.94       972
        7.0       0.95      0.92      0.93      1056
        8.0       0.90      0.89  

In [62]:
print("Accuracy is:",round(metrics.accuracy_score(expected,predicted)*100,2))

Accuracy is: 92.08


In [63]:
print("Test error is:",100-round(metrics.accuracy_score(expected,predicted)*100,2))

Test error is: 7.92


In [64]:
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

Confusion matrix:
[[ 929    1    8    2    2    5    9    3    6    5]
 [   0 1038    8    4    0    4    1    3    5    1]
 [   9   10  883   16    9    2   12   14   14    5]
 [   0    1   23  933    2   30    1    7   27    8]
 [   4    6   11    3  858    1   11    4    2   63]
 [   7    2    1   23    1  841    7    1   25    4]
 [   6    5    7    2   17   16  908    1   10    0]
 [   4    8   22    4   10    5    0  972    8   23]
 [   5    5   21   21    8   10   11    4  922   26]
 [   5    4    3   23   33    8    0   19    5  924]]
